### DISCUSSION TITLE
Sort schema properties?

### DISCUSSION THREAD

**Discussion by luchsamapparat** [thim81/openapi-format#162] [Q&A] [answered]
First of all, great project! It helped me a lot while cleaning up a large, chaotic OpenAPI spec.

One thing I was wondering, is it also possible to sort components/schemas alphabetically?

**before**
```yaml
components:
  schemas:
    UserDto:
      ...
    PostDto:
      ...
    RoleDto:
      ...
```

**after**
```yaml
components:
  schemas:
    PostDto:
      ...
    RoleDto:
      ...
    UserDto:
      ...
```

**Comment by thim81** [comment]
hi @luchsamapparat 

If I'm not mistaken, there is support for sorting the properties by alphabet, by using `--sortComponentsFile`.
I will have to create a little POC to see if my memory is correct, since it has been while that I had to use this.
As soon as I find some spare time, I'll give it spin to verify if `--sortComponentsFile` is the option to use OR if you have time, you can give it a try.

**Reply by luchsamapparat** [reply]
I saw that, but wasn't sure how to use it 🤔

**Reply by thim81** [reply]
I have to agree that the documentation can be improved on how to use it.
By defining which elements that should be sorted, the CLI will sort the elements alphabetically.

I created tests to guard the functionality but also to have examples
Perhaps you can already have a look at the tests:
https://github.com/thim81/openapi-format/tree/main/test/json-sort-request-params
https://github.com/thim81/openapi-format/tree/main/test/yaml-sort-components

**Reply by thim81** [reply, marked as answer]
hi @luchsamapparat 

The --sortComponents works only on the level of the component elements, it does not sort the properties in the elements.

example:

```yaml
components:
  schemas:
    UserDto:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
    AccountDto:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
```

Becomes:

```yaml
components:
  schemas:
    AccountDto:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
    UserDto:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string

```
