### ISSUE TITLE
$ref looses its quotes although the string contains a # (Which enforces the quotes in yaml)

### ISSUE THREAD

**Issue by kurellajunior** [thim81/openapi-format#108]
when having anything like
```yaml
components:
  schemas:
    Case:
      description: Case file subset
      type: object
      properties:
        extern:
          $ref: "domain-types.openapi.yaml#/components/schemas/Extern"
```
opanapi-format will remove the quotes, leading to an invalid yaml, which in turn most Editors they fail to resolve the ref ( because everything after the # is a comment)

local references `$ref: "#/components/schemas/Exetrn"` keep their quotes, so i assume it is a simple oversight somewhere
