### ISSUE TITLE
Overlay bug: cli creates an object instead of array

### ISSUE THREAD

**Issue by sjbenoist** [thim81/openapi-format#157]
When applying an overlay file that updates an OAS file, the CLI gets confused by the overlay instruction, and creates an object with map instead of an array.

Illustration : 

Let's assume that we have an OAS3 file (any will do) and that we add a schema component like this:

  - target: "$.components.schemas"
    update:
      Contact:
        type: object
        properties:
          contact_name:
            type: string
          email:
            type: string
          phone_number:
            type: string
        required: ["contact_name"]

This is a trivial schema object, with 3 properties, one of them being mandatory.
When applying the overlay (openapi-format --overlayFile ....), we obtain this in the output:

      "Contact": {
        "type": "object",
        "properties": {
          "contact_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone_number": {
            "type": "string"
          }
        },
        "required": {
          "0": "contact_name"
        }
      }

Even though I used an array notation ( required: ["contact_name"] instead of a natural block style, the output is a "required" object with a strange "0" key property, typical of a map representation.
The problem is the same when trying to address other array structures in an OAS file, like tags at an operation level.

**Comment by thim81** [comment]
hi @sjbenoist 

I tried to reproduce the reported behaviour in the [online playground](https://openapi-format-playground.vercel.app/?input=H4sIAAAAAAAAA21Qy04DMQy85yt8661d6C03jtwq8QUhNVtXG9uKDVKF%2BHe8hVWXR06O55GZiCIXpQz77bDdJ%2BIXyQnAySfM8FSaTggPh8fYvWE3Es5wF9QhafGTzdydEo%2FzADCifw0A9tpa6ZfwoKvHTALkowqxf3M6mgob2iIC2NwPw%2BZ2BTii1U7q15cPEiaLakWqwo7sax1AUZ2ollm5O1vIf6CRsJ6wld%2Fb6H7RqC7PZ6z%2BB9Quit1pnfl2GpqVEf%2BDFl%2FzHj%2BRqrQoEZktQ1qyxPz%2BkT4Bi%2BAJ6JMBAAA%3D&config=H4sIAAAAAAAAA41SPW%2FCMBD9K5ZViQUiunqNRJdKDKxI6Eguxq3tc%2B1zJVT1v9dxIAUmNr937959%2BUcmiiwVx4xL%2BYkYWnIOPSepBrCpkIOxjHGHRSXlsupn0EEyXs%2BQvjFaOE%2F4ApR4bdbNeu%2BNH0jtvRBs2KISi8UIiigZ8hOEjss7VdVKMESNrMRL05EL5MeumtSd0EEaFULk0AOjmoAQLXkuFjMupc6hVKLjB3b8z4ZIASMbTDdSIbop%2FeDB4V3g6pM4lmlvI6UVY5%2FUhlMZ4eCzO2J8KiXiVzYR%2Bzvx6q7NvS9b1%2Bgxlj3MZzBpU2%2B2DXWdLVkLIWE%2Fn5RJa4tvl7wHuq03fSC30zGvH4Uyh8zv4HUGXQzkGZwtlQPwaVc%2FlKRotPEwsj0OkC1vDNp%2BjFb70ej3D4vqiGx%2FAgAA)

But it looks to work as expected?

![Image](https://github.com/user-attachments/assets/e3f96150-5708-45d3-abe5-b3b708329eae)

OpenAPI overlay:

```yaml
overlay: 1.0.0
info:
  title: ''
  version: ''
actions:
  - target: $.components.schemas
    update:
      Contact:
        type: object
        properties:
          contact_name:
            type: string
          email:
            type: string
          phone_number:
            type: string
        required:
          - contact_name
```

Can you provide more info to reproduce your reported issue?
