### ISSUE TITLE
a "properties" field in the properties cause for splitting of the word

### ISSUE THREAD

**Issue by thim81** [thim81/openapi-format#2]
If you have property named "properties" in the properties object, it converts the object.

OpenAPI

```yaml
components:
  schemas:
    operationsResultData:
      type: object
      properties:
           properties:
                 type: object
```

results in 
```yaml
components:
  schemas:
    operationsResultData:
      type: object
      properties:
               properties:
                      type:
                      '0': o
                      '1': b
                      '2': j
                      '3': e
                      '4': c
                      '5': t
```
