### ISSUE TITLE
"properties" in the examples section gets incorrectly handled 

### ISSUE THREAD

**Issue by thim81** [thim81/openapi-format#3]
If you have property named "properties" in the examples , it converts the object.

OpenAPI
```yaml
  examples:
    sample-example:
      value:
           properties:
                  reportLocation: https://customername.example/1234567890/reports/ABC-123-DEF-456

```
results in

```yaml
  examples:
    sample-example:
      value:
           properties:
                reportLocation:
                     '0': h
                     '1': t
                     '2': t
                    '3': p
```
