### ISSUE TITLE
Restrict casing of operationId

### ISSUE THREAD

**Issue by thim81** [thim81/openapi-format#33]
The `operationId` casing should only be applied in the "path" object, and not in "examples".

```
sample-script-output-failure:
      value:
        operationId: 7e24fadb-c31a-4b47-a8bf-4996900fc6c9
        created: '2020-06-19T12:01:03.456Z'
        lastAction: '2020-06-19T12:06:03.456Z'
```
