### ISSUE TITLE
Illegal OpenAPI after format due to automatic conversion of string attribute to number

### ISSUE THREAD

**Issue by simon-spinner** [thim81/openapi-format#47]
If the `title` attribute of a schema contains only a string that looks like a number, e.g.: "500.1", starting with 1.9.1 openapi-format will turn it into a number in the formatted output (yaml format). The resulting specification is illegal, as the title attribute must always be a string and not a number.

**Comment by thim81** [comment]
@simon-spinner 

Thanks for reporting the issue.

I havent been able to test it myself, but could you already share if this happens everywhere or only certain OAS elements (like schema or components)?

**Comment by thim81** [comment]
@simon-spinner 

I just updated an existing test, where the input/output are the same

```yaml
components:
  schemas:
    Pet:
      type: object
      properties:
        properties:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: 500.1
        name:
          type: string
          example: 123456789012345678901234567890
```

I tried with the exact same numeric value "500.1".

Can you provide me with an example where the conversion is incorrect?
