### ISSUE TITLE
YAML empty objects get sripped away 

### ISSUE THREAD

**Issue by a-waider** [thim81/openapi-format#72]
I've experienced that empty objects in the yaml gets stripped away. An example for a request body in openapi with an epmty object gets stripped away.

E.g.
``` yaml
example:
  default:
    key1: "value1"
    key: {}
```

becomes

``` yaml
example:
  default:
    key1: "value1"
```

Is this related to the parsing library used in openapi-format? Do you have any suggestions how to preserve the empty object?
